name: bns_flat
source_type: bns
description:
    Flat BNS graph preset with ordered component masses on [1.0, 3.0] solar
    masses.
parameters:
    raw_mass_1:
        intermediate: true
        sampler:
            function: uniform
            arguments:
                minimum: 1.0
                maximum: 3.0
    raw_mass_2:
        intermediate: true
        sampler:
            function: uniform
            arguments:
                minimum: 1.0
                maximum: 3.0
    detector_frame_mass_1:
        transform:
            function: maximum
            arguments:
                left: '@raw_mass_1'
                right: '@raw_mass_2'
    detector_frame_mass_2:
        transform:
            function: minimum
            arguments:
                left: '@raw_mass_1'
                right: '@raw_mass_2'
    spin_1x:
        transform:
            function: constant_like
            arguments:
                reference: '@detector_frame_mass_1'
                value: 0.0
    spin_1y:
        transform:
            function: constant_like
            arguments:
                reference: '@detector_frame_mass_1'
                value: 0.0
    spin_1z:
        transform:
            function: constant_like
            arguments:
                reference: '@detector_frame_mass_1'
                value: 0.0
    spin_2x:
        transform:
            function: constant_like
            arguments:
                reference: '@detector_frame_mass_1'
                value: 0.0
    spin_2y:
        transform:
            function: constant_like
            arguments:
                reference: '@detector_frame_mass_1'
                value: 0.0
    spin_2z:
        transform:
            function: constant_like
            arguments:
                reference: '@detector_frame_mass_1'
                value: 0.0
    eccentricity:
        transform:
            function: constant_like
            arguments:
                reference: '@detector_frame_mass_1'
                value: 0.0
    distance:
        sampler:
            function: uniform_comoving_volume_distance
            arguments:
                d_max: 5000.0
    coa_phase:
        transform:
            function: constant_like
            arguments:
                reference: '@distance'
                value: 0.0
    inclination:
        transform:
            function: isotropic_spin_orientation
            arguments:
                reference: '@distance'
    theta_jn:
        transform:
            function: isotropic_spin_orientation
            arguments:
                reference: '@distance'
    long_asc_node:
        transform:
            function: constant_like
            arguments:
                reference: '@distance'
                value: 0.0
    mean_per_ano:
        transform:
            function: constant_like
            arguments:
                reference: '@distance'
                value: 0.0
    coa_time:
        transform:
            function: constant_like
            arguments:
                reference: '@distance'
                value: 0.0
    right_ascension:
        transform:
            function: constant_like
            arguments:
                reference: '@distance'
                value: 0.0
    declination:
        transform:
            function: constant_like
            arguments:
                reference: '@distance'
                value: 0.0
    polarization_angle:
        transform:
            function: constant_like
            arguments:
                reference: '@distance'
                value: 0.0
    redshift:
        transform:
            function: luminosity_distance_to_redshift
            arguments:
                luminosity_distance: '@distance'
    f_ref:
        transform:
            function: constant_like
            arguments:
                reference: '@distance'
                value: 20.0
